/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.35
 * Generated at: 2017-11-03 08:51:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!doctype html>\n");
      out.write("<html lang=\"en\" ng-app=\"webixApp\">\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"utf-8\">\n");
      out.write("        <title>Webix - Angular  : Layouts</title>\n");
      out.write("       <link rel=\"stylesheet\"\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/flatly/bootstrap.min.css\">\n");
      out.write("        <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\n");
      out.write("        <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("        <script src=\"https://ajax.googleapis.com/ajax/libs/angularjs/1.2.4/angular.js\"></script>\n");
      out.write("        <script src=\"https://angular-ui.github.io/ui-router/release/angular-ui-router.js\"></script>\n");
      out.write("\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"https://cdn.webix.com/edge/webix.css\">\n");
      out.write("        <script type=\"text/javascript\" src=\"https://cdn.webix.com/edge/webix.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"JS/index.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"JS/controller.js\"></script>\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"CSS/cust.css\">      \n");
      out.write("    </head>\n");
      out.write("    <body ng-controller=\"TreeController\">\n");
      out.write("\n");
      out.write("        <div webix-ui type=\"space\">\n");
      out.write("            <div height=\"35\">Super Micro Flow Module </div>\n");
      out.write("            <div view=\"resizer\"></div>\n");
      out.write("            <div view=\"cols\" type=\"wide\" margin=\"10\" height=\"850px\">\n");
      out.write("            \n");
      out.write("                <div id=\"\" width=\"250\" height=\"500\">\n");
      out.write("                    <div webix-ui=\"advanceSearch\"></div>\n");
      out.write("                     <div webix-ui=\"treeCombo\"></div>\n");
      out.write("                    <div webix-ui=\"imagebuttons\"></div>\n");
      out.write("                    <input type=\"text\" placeholder=\"Search\" ng-model=\"app\">\n");
      out.write("                    <input type=\"button\" value=\"Go\" style=\"width:50px;\">\n");
      out.write("                    <div webix-ui=\"myTree\" webix-data =\"data_a\" style=\"height: 500px; overflow-y: scroll\"></div>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div view=\"resizer\"></div>\n");
      out.write("                <div view=\"tabview\" css=\"headerStyle\" ng-controller=\"addCtrl\" style=\"height: 4px; overflow-y: scroll\">\n");
      out.write("                    <div  id=\"id_headersup\" header=\"Super Micro Flow\">\n");
      out.write("                        <div webix-ui=\"comboGroup\"></div>\n");
      out.write("                        <div ui-view></div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("           \n");
      out.write("            <div></div>\n");
      out.write("        </div>\n");
      out.write("    </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
